AIS Transponder: fireTestPacket
fireTestPacket()
void fireTestPacket ()
Define a dummy packet of 9600 random bits, so it will take 1 second to transmit. This is long enough for most spectrum analyzers to capture details using "max hold", even at very low resolution bandwidths. Great way to measure power and look for spurious emissions as well as harmonics.
Definition at line 61 of file CommandProcessor.cpp.
{
  VHFChannel channel = CH_87;
  if ( rand() % 2 == 0 )
    channel = CH_88;
  TXPacket *p = TXPacketPool::instance().newTXPacket(channel);
  if ( !p ) {
      //DBG("Ooops! Out of TX packets :(\r\n");
      return;
  }
  p->configureForTesting(channel, 9600);
  RadioManager::instance().sendTestPacketNow(p);
}
References CH_87, CH_88, TXPacket::configureForTesting(), RadioManager::instance(), TXPacketPool::instance(), TXPacketPool::newTXPacket(), and RadioManager::sendTestPacketNow().
Referenced by CommandProcessor::processCommand().