AIS Transponder: termInputCB
termInputCB()
void termInputCB (char c)
Definition at line 99 of file DataTerminal.cpp.
{
  if ( c == '\r' )
    {
      return;
    }
  __rxbuff[__rxpos++] = c;
  if ( __rxpos >= sizeof __rxbuff )
    {
      __rxpos = 0;
    }
  else if ( c == '\n' )
    {
      __rxbuff[__rxpos++] = 0;
      Event *e = EventPool::instance().newEvent(COMMAND_EVENT);
      strlcpy(e->command.buffer, __rxbuff, sizeof e->command.buffer);
      EventQueue::instance().push(e);
      __rxpos = 0;
    }
}
References DebugMessage::buffer, Event::command, COMMAND_EVENT, EventQueue::instance(), EventPool::instance(), EventPool::newEvent(), and EventQueue::push().
Referenced by DataTerminal::init().