AIS Transponder: gnss1PPSCB
gnss1PPSCB()
void gnss1PPSCB ()
Definition at line 320 of file GPS.cpp.
{
  GPS::instance().onPPS();
}
References GPS::instance(), and GPS::onPPS().
Referenced by GPS::init().