AIS Transponder: gnssSOTDMACB
gnssSOTDMACB()
void gnssSOTDMACB ()
Definition at line 325 of file GPS.cpp.
{
  GPS::instance().onTimerIRQ();
}
References GPS::instance(), and GPS::onTimerIRQ().
Referenced by GPS::init().