AIS Transponder: gnssInputCB
gnssInputCB()
void gnssInputCB (char c)
Definition at line 315 of file GPS.cpp.
{
  GPS::instance().onRX(c);
}
References GPS::instance(), and GPS::onRX().
Referenced by GPS::init().