AIS Transponder: bsp_tx_led_off
bsp_tx_led_off()
void bsp_tx_led_off ()
Definition at line 535 of file bsp_11_3.cpp.
{
#if LEGACY_BREAKOUTS
  HAL_GPIO_WritePin(TX_EVT_PORT, TX_EVT_PIN, GPIO_PIN_SET);
#else
  HAL_GPIO_WritePin(TX_EVT_PORT, TX_EVT_PIN, GPIO_PIN_RESET);
#endif
}
References TX_EVT_PIN, and TX_EVT_PORT.
Referenced by LEDManager::init(), LEDManager::onTick(), and Transceiver::reportTXEvent().