AIS Transponder: bsp_reboot
bsp_reboot()
void bsp_reboot ()
Definition at line 685 of file bsp_11_3.cpp.
{
  NVIC_SystemReset();
}
Referenced by CommandProcessor::enterCLIMode(), CommandProcessor::processCommand(), and RadioManager::processEvent().