AIS Transponder: tickCB
tickCB()
void tickCB ()
Definition at line 37 of file LEDManager.cpp.
{
  LEDManager::instance().onTick();
}
References LEDManager::instance(), and LEDManager::onTick().
Referenced by LEDManager::init().