AIS Transponder: bsp_enter_dfu
bsp_enter_dfu()
void bsp_enter_dfu ()
Definition at line 695 of file bsp_11_3.cpp.
{
  // Cut off the GPS signals immediately to prevent its UART from transmitting and hijacking the bootloader upon reset
  bsp_gnss_off();
  HAL_Delay(1000);
  // This flag simply tells main() to jump to the ROM bootloader immediately upon reset, before initializing anything
  *(uint32_t*)BOOTMODE_ADDRESS = DFU_FLAG_MAGIC;
  bsp_reboot();
}
References BOOTMODE_ADDRESS, bsp_gnss_off(), bsp_reboot(), and DFU_FLAG_MAGIC.
Referenced by CommandProcessor::jumpToBootloader().