AIS Transponder: bsp_gnss_off
bsp_gnss_off()
void bsp_gnss_off ()
Definition at line 571 of file bsp_11_3.cpp.
{
  HAL_GPIO_WritePin(GNSS_EN_PORT, GNSS_EN_PIN, GPIO_PIN_SET);
}
References GNSS_EN_PIN, and GNSS_EN_PORT.
Referenced by bsp_enter_dfu(), GPS::disable(), and CommandProcessor::processCommand().