AIS Transponder: bsp_write_config_flags
bsp_write_config_flags()
void bsp_write_config_flags (const ConfigFlags & flags)
Definition at line 459 of file bsp_11_3.cpp.
{
  ConfigFlags __f = flags;
  uint8_t *d = (uint8_t*)&__f;
  for ( uint8_t i = 0; i < sizeof (ConfigFlags); ++i, ++d )
    {
      HAL_I2C_Mem_Write(&hi2c1, EEPROM_ADDRESS, i+EEPROM_CONFIG_ADDRESS, 1, d, 1, 5);
      HAL_Delay(5);
    }
}
References EEPROM_ADDRESS, EEPROM_CONFIG_ADDRESS, and hi2c1.
Referenced by bsp_erase_config_flags(), Configuration::disableTX(), and Configuration::enableTX().