AIS Transponder: bsp_erase_station_data
bsp_erase_station_data()
void bsp_erase_station_data ()
Definition at line 440 of file bsp_11_3.cpp.
{
  bsp_write_station_data({0});
}
References bsp_write_station_data().
Referenced by Configuration::eraseStationData(), and Configuration::factoryReset().