AIS Transponder: bsp_write_string
bsp_write_string()
void bsp_write_string (const char * s)
Definition at line 594 of file bsp_11_3.cpp.
{
  for ( int i = 0; s[i] != 0; ++i )
    USART_putc(USART1, s[i]);
}
References USART_putc().
Referenced by printf_serial(), printf_serial_now(), and DataTerminal::write().