AIS Transponder: GPS::onRX
onRX()
void GPS::onRX (char c)
Definition at line 109 of file GPS.cpp.
{
  // This code is called in interrupt mode, do as little as possible!
  mBuff[mBuffPos++] = c;
  if (mBuffPos > 90)
    {
      // We screwed up!
      mBuffPos = 0;
      mBuff[mBuffPos] = 0;
    }
  else if (c == '\n')
    {
      mBuff[mBuffPos] = 0;
      Event *e = EventPool::instance().newEvent(GPS_NMEA_SENTENCE);
      if ( e )
        {
          strlcpy(e->nmeaBuffer.sentence, mBuff, sizeof e->nmeaBuffer.sentence);
          EventQueue::instance ().push(e);
        }
      mBuffPos = 0;
      mBuff[mBuffPos] = 0;
    }
}
References GPS_NMEA_SENTENCE, EventQueue::instance(), EventPool::instance(), mBuff, mBuffPos, EventPool::newEvent(), Event::nmeaBuffer, EventQueue::push(), and NMEABuffer::sentence.
Referenced by gnssInputCB().