AIS Transponder: RadioManager::start
start()
void RadioManager::start ()
Definition at line 106 of file RadioManager.cpp.
{
  configureInterrupts();
  if ( mTransceiverIC )
    mTransceiverIC->startReceiving(CH_87, true);
  if ( mReceiverIC )
    mReceiverIC->startReceiving(CH_88, true);
  GPS::instance().setDelegate(this);
}
References CH_87, CH_88, configureInterrupts(), GPS::instance(), mReceiverIC, mTransceiverIC, GPS::setDelegate(), Receiver::startReceiving(), and Transceiver::startReceiving().
Referenced by mainLoop().