AIS Transponder: LEDManager::onTick
onTick()
void LEDManager::onTick ()
Definition at line 52 of file LEDManager.cpp.
{
  static int count1 = 1;
  static int count2 = 1;
  if ( count1++ % 20 == 0 )
    {
      count1 = 1;
      bsp_rx_led_off();
    }
  if ( count2++ == 200 )
    {
      count2 = 1;
      if ( TXScheduler::instance().isTXAllowed() )
        bsp_tx_led_on();
      else
        bsp_tx_led_off();
    }
}
References bsp_rx_led_off(), bsp_tx_led_off(), bsp_tx_led_on(), and TXScheduler::instance().
Referenced by tickCB().