AIS Transponder: RFIC::readSPIResponse
readSPIResponse()
bool RFIC::readSPIResponse (void * data, uint8_t len) private
Definition at line 139 of file RFIC.cpp.
{
  spiOn();
  bsp_tx_spi_byte(0x44);
  if ( bsp_tx_spi_byte(0) != 0xff )
    {
      spiOff();
      return false;
    }
  if ( data )
    {
      uint8_t* b = (uint8_t*) data;
      uint8_t i = 0;
      while (i < length)
        {
          b[i] = bsp_tx_spi_byte(0);
          ++i;
        }
    }
  spiOff();
  return true;
}
References bsp_tx_spi_byte(), spiOff(), and spiOn().
Referenced by sendCmd(), and sendCmdNoWait().