AIS Transponder: RFIC::setXOTrimValue
setXOTrimValue()
void RFIC::setXOTrimValue (uint8_t value)
Definition at line 198 of file RFIC.cpp.
{
  SET_PROPERTY_PARAMS params = {0};
  params.Group          = 0;
  params.NumProperties  = 2;
  params.StartProperty  = 0;
  params.Data[0] = value;
  sendCmd(SET_PROPERTY, &params, sizeof params, NULL, 0);
}
References SET_PROPERTY_PARAMS::Data, SET_PROPERTY_PARAMS::Group, SET_PROPERTY_PARAMS::NumProperties, sendCmd(), SET_PROPERTY, and SET_PROPERTY_PARAMS::StartProperty.
Referenced by configure(), and RadioManager::setXOTrimValue().