AIS Transponder: RadioManager::processEvent
processEvent()
void RadioManager::processEvent (const Event & e) virtual
For some reason, RX performance seems to go downhill after many hours of continuous operation, so the easiest remedy is to reboot every hour. The impact of this is pretty small.
Implements EventConsumer.
Definition at line 140 of file RadioManager.cpp.
{
  mUTC = e.clock.utc;
  if ( mStartTime == 0 )
    {
      mStartTime = mUTC;
    }
  if ( !mTXQueue.empty() && mTransceiverIC->assignedTXPacket() == NULL )
    {
      // There is no current TX operation pending, so we assign one
      TXPacket *packet = NULL;
      mTXQueue.pop(packet);
      ASSERT(packet);
      VHFChannel txChannel = packet->channel();
      // Do we need to swap channels?
      if ( txChannel != mTransceiverIC->channel() )
        {
          // The receiver needs to be explicitly told to switch channels
          if ( mReceiverIC )
            mReceiverIC->switchToChannel(alternateChannel(txChannel));
        }
      // The transceiver will switch channel if the packet channel is different
      mTransceiverIC->assignTXPacket(packet);
    }
  else if ( mUTC - mStartTime >= 3600 )
    {
      bsp_reboot();
    }
}
References alternateChannel(), ASSERT, Transceiver::assignedTXPacket(), Transceiver::assignTXPacket(), bsp_reboot(), Receiver::channel(), TXPacket::channel(), Event::clock, CircularQueue< T >::empty(), mReceiverIC, mStartTime, mTransceiverIC, mTXQueue, mUTC, CircularQueue< T >::pop(), Receiver::switchToChannel(), and ClockTick::utc.