AIS Transponder: RXPacket::channel
channel()
VHFChannel RXPacket::channel () const
Definition at line 42 of file RXPacket.cpp.
{
  return mState.mChannel;
}
References mState.
Referenced by NMEAEncoder::encode(), RXPacketProcessor::processEvent(), and setChannel().