AIS Transponder: Receiver::onBitClock
onBitClock()
void Receiver::onBitClock () virtual
Reimplemented in Transceiver.
Definition at line 112 of file Receiver.cpp.
{
  ++mSlotBitNumber;
  // Don't waste time processing bits when the transceiver is transmitting
  if ( gRadioState == RADIO_TRANSMITTING )
    {
      return;
    }
  if ( !mRXPacket )
    {
      mRXPacket = EventPool::instance().newRXPacket();
      if ( !mRXPacket )
        {
          return;
        }
    }
  uint8_t bit = HAL_GPIO_ReadPin(mDataPort, mDataPin);
  Receiver::Action action = processNRZIBit(bit);
  if ( action == RESTART_RX )
    {
      startReceiving(mNextChannel, false);
    }
  else if ( mTimeSlot != 0xffffffff && mSlotBitNumber != 0xffff && mSlotBitNumber == CCA_SLOT_BIT )
    {
      mRXPacket->setRSSI(reportRSSI());
    }
}
References CCA_SLOT_BIT, EventPool::instance(), RFIC::mDataPin, RFIC::mDataPort, mNextChannel, mRXPacket, mSlotBitNumber, mTimeSlot, EventPool::newRXPacket(), processNRZIBit(), RADIO_TRANSMITTING, reportRSSI(), RESTART_RX, RXPacket::setRSSI(), and startReceiving().
Referenced by Transceiver::onBitClock(), and RadioManager::onBitClock().