AIS Transponder: EventPool::newEvent
newEvent()
Event * EventPool::newEvent (EventType type)
Definition at line 72 of file Events.cpp.
{
  Event *result = nullptr;
  if ( Utils::inISR() )
    {
      result = mISRPool.get();
      if ( result )
        {
          result->type = type;
          result->flags = 1;
          ASSERT(!result->rxPacket);
        }
    }
  else
    {
      result = mThreadPool.get();
      if ( result )
        {
          result->type = type;
          result->flags = 0;
          ASSERT(!result->rxPacket);
        }
    }
  //if ( !result)
    //printf2_now("\r\n[DEBUG]newEvent(0x%.8x) failed\r\n", type);
  if ( result == nullptr )
    return result;
  ASSERT_VALID_PTR(result);
  return result;
}
References ASSERT, ASSERT_VALID_PTR, Event::flags, ObjectPool< T >::get(), Utils::inISR(), mISRPool, mThreadPool, Event::rxPacket, and Event::type.
Referenced by NoiseFloorDetector::dump(), Transceiver::onBitClock(), GPS::onPPS(), GPS::onRX(), GPS::parseSentence(), printf_serial(), Receiver::pushPacket(), RadioManager::reportError(), Configuration::reportStationData(), Configuration::reportSystemData(), Transceiver::reportTXEvent(), TXScheduler::reportTXStatus(), Configuration::reportXOTrimValue(), RadioManager::scheduleTransmission(), TXScheduler::sendNMEASentence(), and termInputCB().