AIS Transponder: Receiver::init
init()
bool Receiver::init ()
Definition at line 56 of file Receiver.cpp.
{
  configure();
  resetBitScanner();
  return true;
}
References RFIC::configure(), and resetBitScanner().
Referenced by RadioManager::init().