AIS Transponder: TXPacket::messageType
messageType()
const char * TXPacket::messageType ()
Definition at line 86 of file TXPacket.cpp.
{
  return mMessageType;
}
References mMessageType.
Referenced by Transceiver::onBitClock(), Transceiver::reportTXEvent(), and RadioManager::scheduleTransmission().