AIS Transponder: RFIC::sendCmd
sendCmd()
bool RFIC::sendCmd (uint8_t cmd, void * params, uint8_t paramLen, void * result, uint8_t resultLen) protected
Definition at line 80 of file RFIC.cpp.
{
  if ( mCTSPending )
    {
      while ( readSPIResponse(NULL, 0) == false)
        ;
      mCTSPending = false;
    }
  //bsp_signal_high();
  spiOn();
  bsp_tx_spi_byte(cmd);
  if ( params )
    {
      uint8_t *b = (uint8_t*) params;
      for ( int i = 0; i < paramLen; ++i )
        {
          bsp_tx_spi_byte(b[i]);
        }
    }
  spiOff();
  //bsp_signal_low();
  //bsp_signal_high();
  while ( readSPIResponse(result, resultLen) == false)
    ;
  //bsp_signal_low();
  return true;
}
References bsp_tx_spi_byte(), mCTSPending, readSPIResponse(), spiOff(), and spiOn().
Referenced by checkStatus(), configure(), Transceiver::configure(), Receiver::configureGPIOsForRX(), Transceiver::configureGPIOsForRX(), Transceiver::configureGPIOsForTX(), isInitialized(), readRSSI(), Transceiver::setTXPower(), setXOTrimValue(), Transceiver::startTransmitting(), and Transceiver::transmitCW().