AIS Transponder: Configuration::instance
instance()
Configuration & Configuration::instance () static
Definition at line 40 of file Configuration.cpp.
{
  static Configuration __instance;
  return __instance;
}
Referenced by RFIC::configure(), TXScheduler::init(), TXScheduler::isTXAllowed(), mainLoop(), CommandProcessor::processCommand(), TXScheduler::reportTXStatus(), and RXPacketProcessor::RXPacketProcessor().