AIS Transponder: Receiver::startListening
startListening()
void Receiver::startListening (VHFChannel channel, bool reconfigGPIOs) protected
This never takes more than 65us now :D
Definition at line 76 of file Receiver.cpp.
{
  if ( reconfigGPIOs )
    {
      // This takes about 140us
      configureGPIOsForRX();
    }
  mChannel = channel;
  RX_OPTIONS options;
  options.channel = AIS_CHANNELS[channel].ordinal;
  options.condition = 0;
  options.rx_len = 0;
  options.next_state1 = 0;
  options.next_state2 = 0;
  options.next_state3 = 0;
  sendCmdNoWait(START_RX, &options, sizeof options);
}
References RX_OPTIONS::channel, channel(), RX_OPTIONS::condition, configureGPIOsForRX(), mChannel, RX_OPTIONS::next_state1, RX_OPTIONS::next_state2, RX_OPTIONS::next_state3, RX_OPTIONS::rx_len, RFIC::sendCmdNoWait(), and START_RX.
Referenced by startReceiving().