AIS Transponder: GPS::GPS
GPS()
GPS::GPS () private
Definition at line 43 of file GPS.cpp.
: mBuffPos(0), mUTC(0), mLat(0), mLng(0), mStarted(false), mSlotNumber(0), mDelegate(NULL), mCOG(511), mSpeed(0)
{
  memset(&mTime, 0, sizeof(mTime));
  mPeriod = (bsp_get_system_clock() / 37.5) - 1;
  EventQueue::instance().addObserver(this, GPS_NMEA_SENTENCE);
}
References EventQueue::addObserver(), bsp_get_system_clock(), GPS_NMEA_SENTENCE, EventQueue::instance(), mPeriod, and mTime.