AIS Transponder: TXScheduler::reportTXStatus
reportTXStatus()
void TXScheduler::reportTXStatus ()
Definition at line 75 of file TXScheduler.cpp.
{
  bool hwSwitchOff = bsp_is_tx_disabled();
  bool softSwitch = Configuration::instance().isTXEnabled();
//  bool hasStation = Configuration::instance().isStationDataProvisioned();
  bool hasStation = true; //Added by ishan
  bool status = hwSwitchOff ? false : (softSwitch && hasStation);
  Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
  if ( !e )
    return;
  sprintf(e->nmeaBuffer.sentence, "$PAITXCFG,%d,%d,%d,%d,%d*", bsp_is_tx_hardwired(), !hwSwitchOff, softSwitch, hasStation, status);
  Utils::completeNMEA(e->nmeaBuffer.sentence);
  EventQueue::instance().push(e);
}
References bsp_is_tx_disabled(), bsp_is_tx_hardwired(), Utils::completeNMEA(), Configuration::instance(), EventQueue::instance(), EventPool::instance(), Configuration::isTXEnabled(), EventPool::newEvent(), Event::nmeaBuffer, PROPR_NMEA_SENTENCE, EventQueue::push(), and NMEABuffer::sentence.
Referenced by init(), and CommandProcessor::processCommand().