AIS Transponder: RadioManager::instance
instance()
RadioManager & RadioManager::instance () static
Definition at line 30 of file RadioManager.cpp.
{
  static RadioManager __instance;
  return __instance;
}
Referenced by fireTestPacket(), mainLoop(), CommandProcessor::processCommand(), TXScheduler::processEvent(), TXScheduler::queueMessage18(), TXScheduler::queueMessage24(), rxClockCB(), and trxClockCB().