AIS Transponder: RFIC::sendCmdNoWait
sendCmdNoWait()
bool RFIC::sendCmdNoWait (uint8_t cmd, void * params, uint8_t paramLen) protected
Definition at line 113 of file RFIC.cpp.
{
  if ( mCTSPending )
    {
      while ( readSPIResponse(NULL, 0) == false)
        ;
      mCTSPending = false;
    }
  spiOn();
  bsp_tx_spi_byte(cmd);
  uint8_t *b = (uint8_t*) params;
  for ( int i = 0; i < paramLen; ++i )
    {
      bsp_tx_spi_byte(b[i]);
    }
  spiOff();
  mCTSPending = true;
  return true;
}
References bsp_tx_spi_byte(), mCTSPending, readSPIResponse(), spiOff(), and spiOn().
Referenced by Receiver::startListening().