AIS Transponder: Receiver::reportRSSI
reportRSSI()
uint8_t Receiver::reportRSSI () protected
This operation typically takes under 85us
Definition at line 309 of file Receiver.cpp.
{
  uint8_t rssi = readRSSI();
  char channel = AIS_CHANNELS[mChannel].designation;
  NoiseFloorDetector::instance().report(channel, rssi);
  return rssi;
}
References channel(), NoiseFloorDetector::instance(), mChannel, RFIC::readRSSI(), and NoiseFloorDetector::report().
Referenced by onBitClock().