AIS Transponder: Transceiver::startReceiving
startReceiving()
void Transceiver::startReceiving (VHFChannel channel, bool reconfigGPIOs) virtual
Reimplemented from Receiver.
Definition at line 325 of file Transceiver.cpp.
{
  Receiver::startReceiving(channel, reconfigGPIOs);
}
References Receiver::channel(), and Receiver::startReceiving().
Referenced by onBitClock(), RadioManager::start(), RadioManager::stopTX(), timeSlotStarted(), and transmitCW().