AIS Transponder: TXPacketPool::instance
instance()
TXPacketPool & TXPacketPool::instance () static
Definition at line 153 of file TXPacket.cpp.
{
  static TXPacketPool __instance;
  return __instance;
}
Referenced by fireTestPacket(), mainLoop(), Transceiver::onBitClock(), TXScheduler::queueMessage18(), TXScheduler::queueMessage24(), and RadioManager::scheduleTransmission().