AIS Transponder: Utils::inISR
inISR()
bool Utils::inISR () static
Definition at line 201 of file Utils.cpp.
{
  return __get_IPSR();
}
Referenced by EventPool::newEvent(), printf_serial(), and EventQueue::push().