AIS Transponder: AISMessage::addBits
addBits()
void AISMessage::addBits (uint8_t * buff, uint16_t & size, uint32_t value, uint8_t numBits) protected
Definition at line 75 of file AISMessages.cpp.
{
  ASSERT(numBits > 0  && numBits <= 32);
  uint16_t pos = size;
  for ( uint8_t bit = 0; bit < numBits; ++bit, value >>= 1 )  {
      bitVector[pos + numBits-bit-1] = value & 1;
  }
  size += numBits;
}
References ASSERT.
Referenced by addString(), constructHDLCFrame(), AISMessage18::encode(), AISMessage24A::encode(), AISMessage24B::encode(), and finalize().