AIS Transponder: Transceiver::timeSlotStarted
timeSlotStarted()
void Transceiver::timeSlotStarted (uint32_t slot) virtual
This is called from the SOTDMA timer interrupt, which is at the same priority as the bit clock. So timeSlotStarted() and onBitClock() cannot preempt each other.
Reimplemented from Receiver.
Definition at line 290 of file Transceiver.cpp.
{
  Receiver::timeSlotStarted(slot);
  // Switch channel if we have a transmission scheduled and we're not on the right channel
  if ( gRadioState == RADIO_RECEIVING && mTXPacket && mTXPacket->channel() != mChannel )
    startReceiving(mTXPacket->channel(), false);
}
References TXPacket::channel(), Receiver::mChannel, mTXPacket, RADIO_RECEIVING, startReceiving(), and Receiver::timeSlotStarted().
Referenced by RadioManager::timeSlotStarted().