AIS Transponder: AISMessage::addString
addString()
void AISMessage::addString (uint8_t * buff, uint16_t & size, const std::string & name, uint8_t maxChars) protected
Definition at line 105 of file AISMessages.cpp.
{
  ASSERT(value.length() <= maxChars);
  ASSERT(maxChars < 30); // There should be no application for such long strings here
  char s[30];
  memset(s, 0, sizeof s);
  strncpy(s, value.c_str(), value.length());
  uint8_t buffer[32];
  for ( uint8_t c = 0; c < maxChars; ++c ) {
      uint8_t byte = s[c] >= 64 ? s[c]-64 : s[c];
      buffer[c] = byte;
  }
  for ( uint8_t c = 0; c < maxChars; ++c )
    addBits(bitVector, size, buffer[c], 6);
}
References addBits(), and ASSERT.
Referenced by AISMessage24A::encode(), and AISMessage24B::encode().