AIS Transponder: TXScheduler::sendNMEASentence
sendNMEASentence()
void TXScheduler::sendNMEASentence (const char * sentence) private
Definition at line 175 of file TXScheduler.cpp.
{
  Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
  if ( !e )
    return;
  strlcpy(e->nmeaBuffer.sentence, sentence, sizeof e->nmeaBuffer.sentence);
  Utils::completeNMEA(e->nmeaBuffer.sentence);
  EventQueue::instance().push(e);
}
References Utils::completeNMEA(), EventQueue::instance(), EventPool::instance(), EventPool::newEvent(), Event::nmeaBuffer, PROPR_NMEA_SENTENCE, EventQueue::push(), and NMEABuffer::sentence.
Referenced by queueMessage18(), and queueMessage24().