AIS Transponder: RXPacket::messageType
messageType()
uint8_t RXPacket::messageType () const
Definition at line 244 of file RXPacket.cpp.
{
  if ( mState.mType )
    return mState.mType;
  for ( int i = 0; i < 6; ++i ) {
      mState.mType <<= 1;
      mState.mType |= bit(i);
  }
  return mState.mType;
}
References bit(), and mState.
Referenced by AISMessage15::decode(), and RXPacketProcessor::processEvent().