AIS Transponder: RXPacketProcessor::RXPacketProcessor
RXPacketProcessor()
RXPacketProcessor::RXPacketProcessor ()
Definition at line 39 of file RXPacketProcessor.cpp.
{
  mSentences.reserve(4); // We're not going to need more than 2 sentences for the longest AIS message we report ...
  Configuration::instance().readStationData(mStationData);
  EventQueue::instance().addObserver(this, AIS_PACKET_EVENT);
}
References EventQueue::addObserver(), AIS_PACKET_EVENT, Configuration::instance(), EventQueue::instance(), mSentences, mStationData, and Configuration::readStationData().