AIS Transponder: Configuration::factoryReset
factoryReset()
void Configuration::factoryReset ()
Definition at line 222 of file Configuration.cpp.
{
  bsp_erase_station_data();
  mFlags = {0};
  bsp_erase_config_flags();
  bsp_erase_xo_trim();
}
References bsp_erase_config_flags(), bsp_erase_station_data(), bsp_erase_xo_trim(), and mFlags.
Referenced by CommandProcessor::processCommand().