AIS Transponder: Configuration::reportXOTrimValue
reportXOTrimValue()
void Configuration::reportXOTrimValue ()
Definition at line 204 of file Configuration.cpp.
{
  uint8_t value = 0;
  if ( this->isXOTrimmed() )
    {
      value = this->getXOTrimValue();
    }
  Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
  if ( !e )
    return;
  sprintf(e->nmeaBuffer.sentence, "$PAIXOTR,%d*", value);
  Utils::completeNMEA(e->nmeaBuffer.sentence);
  EventQueue::instance().push(e);
}
References Utils::completeNMEA(), getXOTrimValue(), EventQueue::instance(), EventPool::instance(), isXOTrimmed(), EventPool::newEvent(), Event::nmeaBuffer, PROPR_NMEA_SENTENCE, EventQueue::push(), and NMEABuffer::sentence.
Referenced by CommandProcessor::processCommand().