AIS Transponder: AISMessage18::encode
encode()
void AISMessage18::encode (const StationData & data, TXPacket & packet) virtual
Encodes AIS message 18 into a transmit packet.
Parameters
data The station data to be included in the message.
packet The TXPacket to store the encoded message.
Reimplemented from AISMessage.
Definition at line 294 of file AISMessages.cpp.
{
  AISMessage::encode(station, packet);
  // TODO: Perhaps this shouldn't live on the stack?
  uint8_t payload[MAX_AIS_TX_PACKET_SIZE];
  uint16_t size = 0;
  uint32_t value;
  packet.setMessageType("18");
  value = mType;
  addBits(payload, size, value, 6);   // Message type
  value = mRI;
  addBits(payload, size, value, 2);   // Repeat Indicator
  value = mMMSI;
  addBits(payload, size, value, 30);  // MMSI
  value = 0;
  addBits(payload, size, value, 8);   // Spare bits
  value = (uint32_t)(sog * 10);
  addBits(payload, size, value, 10);  // Speed (knots x 10)
  value = 1;
  addBits(payload, size, value, 1);   // Position accuracy is high
  value = Utils::coordinateToUINT32(longitude);
  addBits(payload, size, value, 28);  // Longitude
  value = Utils::coordinateToUINT32(latitude);
  addBits(payload, size, value, 27);  // Latitude
  value = (uint32_t)(cog * 10);
  addBits(payload, size, value, 12);  // COG
  value = 511;
  addBits(payload, size, value, 9);   // We don't know our heading
  value = utc % 60;
  addBits(payload, size, value, 6);   // UTC second.
  value = 0;
  addBits(payload, size, value, 2);   // Spare
  value = 1;
  addBits(payload, size, value, 1);   // We are a "CS" unit
  value = 0;
  addBits(payload, size, value, 1);   // We have no display
  value = 0;
  addBits(payload, size, value, 1);   // We have no DSC
  value = 0;
  addBits(payload, size, value, 1);   // We don't switch frequencies so this doesn't matter
  value = 0;
  addBits(payload, size, value, 1);   // We do not respond to message 22 to switch frequency
  value = 0;
  addBits(payload, size, value, 1);   // We operate in autonomous and continuous mode
  value = 0;
  addBits(payload, size, value, 1);   // No RAIM
  value = 1;
  addBits(payload, size, value, 1);   // We use ITDMA (as a CS unit)
  value = DEFAULT_COMM_STATE;
  addBits(payload, size, value, 19);  // Standard communication state flag for CS units
#if DEV_MODE
  ASSERT(size == 168);
#endif
  finalize(payload, size, packet);
}
References AISMessage::addBits(), ASSERT, cog, Utils::coordinateToUINT32(), DEFAULT_COMM_STATE, AISMessage::encode(), AISMessage::finalize(), latitude, longitude, MAX_AIS_TX_PACKET_SIZE, AISMessage::mMMSI, AISMessage::mRI, AISMessage::mType, TXPacket::setMessageType(), sog, and utc.
Referenced by TXScheduler::queueMessage18().