AIS Transponder: Transceiver::configureGPIOsForTX
configureGPIOsForTX()
void Transceiver::configureGPIOsForTX () private
Definition at line 152 of file Transceiver.cpp.
{
  bsp_set_tx_mode();
  GPIO_PIN_CFG_PARAMS gpiocfg;
  gpiocfg.GPIO0 = 0x00;       // No change
  gpiocfg.GPIO1 = 0x04;       // RX/TX bit data
  gpiocfg.GPIO2 = 0x1F;       // RX/TX bit clock
#if BOARD_REV < 105
  gpiocfg.GPIO3 = 0x21;       // RX_STATE; low during TX and high during RX
#else
  gpiocfg.GPIO3 = 0x20;       // RX_STATE; high during TX and low during RX
#endif
  gpiocfg.NIRQ  = 0x00;       // No change
  gpiocfg.SDO   = 0x00;       // No change
  gpiocfg.GENCFG = 0x00;      // No change
  sendCmd(GPIO_PIN_CFG, &gpiocfg, sizeof gpiocfg, NULL, 0);
}
References bsp_set_tx_mode(), GPIO_PIN_CFG_PARAMS::GENCFG, GPIO_PIN_CFG_PARAMS::GPIO0, GPIO_PIN_CFG_PARAMS::GPIO1, GPIO_PIN_CFG_PARAMS::GPIO2, GPIO_PIN_CFG_PARAMS::GPIO3, GPIO_PIN_CFG, GPIO_PIN_CFG_PARAMS::NIRQ, GPIO_PIN_CFG_PARAMS::SDO, and RFIC::sendCmd().
Referenced by startTransmitting(), and transmitCW().