AIS Transponder: RadioManager::configureInterrupts
configureInterrupts()
void RadioManager::configureInterrupts () private
Definition at line 134 of file RadioManager.cpp.
{
  bsp_set_trx_clk_callback(trxClockCB);
  bsp_set_rx_clk_callback(rxClockCB);
}
References bsp_set_rx_clk_callback(), bsp_set_trx_clk_callback(), rxClockCB(), and trxClockCB().
Referenced by start().