AIS Transponder: Transceiver::startTransmitting
startTransmitting()
void Transceiver::startTransmitting () private
Definition at line 299 of file Transceiver.cpp.
{
  // Configure the RFIC GPIOs for transmission
  // Configure the pin for GPIO 1 as output
  // Set TX power level
  // Start transmitting
  gRadioState = RADIO_TRANSMITTING;
  configureGPIOsForTX();
  //ASSERT(false);
  TX_OPTIONS options;
  options.channel     = AIS_CHANNELS[mTXPacket->channel()].ordinal;
  options.condition   = 0;
  options.tx_len      = 0;
  options.tx_delay    = 0;
  options.repeats     = 0;
  sendCmd(START_TX, &options, sizeof options, NULL, 0);
  // Ensure all data changes in the function have completed, otherwise gRadioState may not actually be modified
  __DSB();
}
References TX_OPTIONS::channel, TXPacket::channel(), TX_OPTIONS::condition, configureGPIOsForTX(), mTXPacket, RADIO_TRANSMITTING, TX_OPTIONS::repeats, RFIC::sendCmd(), START_TX, TX_OPTIONS::tx_delay, and TX_OPTIONS::tx_len.
Referenced by onBitClock().