AIS Transponder: EventQueue::push
push()
bool EventQueue::push (Event * event)
Definition at line 43 of file EventQueue.cpp.
{
  if ( Utils::inISR() )
    {
      if ( !mISRQueue.push(e) )
        {
          EventPool::instance().deleteEvent(e);
          return false;
        }
    }
  else
    {
      if ( !mTaskQueue.push(e) )
        {
          EventPool::instance().deleteEvent(e);
          return false;
        }
    }
  return true;
}
References EventPool::deleteEvent(), Utils::inISR(), EventPool::instance(), mISRQueue, mTaskQueue, and CircularQueue< T >::push().
Referenced by NoiseFloorDetector::dump(), Transceiver::onBitClock(), GPS::onPPS(), GPS::onRX(), GPS::parseSentence(), printf_serial(), RXPacketProcessor::processEvent(), RadioManager::reportError(), Configuration::reportStationData(), Configuration::reportSystemData(), Transceiver::reportTXEvent(), TXScheduler::reportTXStatus(), Configuration::reportXOTrimValue(), RadioManager::scheduleTransmission(), TXScheduler::sendNMEASentence(), and termInputCB().