AIS Transponder: RFIC::configure
configure()
void RFIC::configure () protected virtual
Reimplemented in Transceiver.
Definition at line 164 of file RFIC.cpp.
{
  PART_INFO_REPLY reply;
  sendCmd(PART_INFO, nullptr, 0, &reply, sizeof reply);
  mPartNumber = reply.PartNumberH << 8 | reply.PartNumberL;
  uint8_t *radio_configuration = nullptr;
  switch(mPartNumber)
  {
  case 0x4467:
    radio_configuration = get_si4467_config_array();
    break;
  case 0x4460:
    radio_configuration = get_si4460_config_array();
    break;
  default:
    radio_configuration = get_si4463_config_array();
  }
  uint8_t *cfg = radio_configuration;
  while (*cfg)
    {                              // configuration array stops with 0
      uint8_t count = (*cfg++) - 1;           // 1st byte: number of bytes, incl. command
      uint8_t cmd = *cfg++;                   // 2nd byte: command
      sendCmd(cmd, cfg, count, NULL, 0);      // send bytes to chip
      cfg += count;                           // point at next line
    }
  if ( Configuration::instance().isXOTrimmed() )
    {
      setXOTrimValue(Configuration::instance().getXOTrimValue());
    }
}
References get_si4460_config_array(), get_si4463_config_array(), get_si4467_config_array(), Configuration::instance(), mPartNumber, PART_INFO, PART_INFO_REPLY::PartNumberH, PART_INFO_REPLY::PartNumberL, sendCmd(), and setXOTrimValue().
Referenced by Transceiver::configure(), and Receiver::init().