AIS Transponder: DataTerminal::init
init()
void DataTerminal::init ()
Definition at line 37 of file DataTerminal.cpp.
{
  bsp_set_terminal_input_callback(termInputCB);
}
References bsp_set_terminal_input_callback(), and termInputCB().
Referenced by mainLoop().