AIS Transponder: Transceiver::reportTXEvent
reportTXEvent()
void Transceiver::reportTXEvent () private
Definition at line 349 of file Transceiver.cpp.
{
  Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
  if ( !e )
    return;
  snprintf(e->nmeaBuffer.sentence, sizeof e->nmeaBuffer.sentence, "$PAITX,%c,%s*", AIS_CHANNELS[mTXPacket->channel()].designation, mTXPacket->messageType());
  Utils::completeNMEA(e->nmeaBuffer.sentence);
  EventQueue::instance().push(e);
  bsp_tx_led_off();
}
References bsp_tx_led_off(), TXPacket::channel(), Utils::completeNMEA(), EventQueue::instance(), EventPool::instance(), TXPacket::messageType(), mTXPacket, EventPool::newEvent(), Event::nmeaBuffer, PROPR_NMEA_SENTENCE, EventQueue::push(), and NMEABuffer::sentence.
Referenced by onBitClock().