AIS Transponder: GPS::instance
instance()
GPS & GPS::instance () static
Definition at line 37 of file GPS.cpp.
{
  static GPS __instance;
  return __instance;
}
Referenced by gnss1PPSCB(), gnssInputCB(), gnssSOTDMACB(), mainLoop(), and RadioManager::start().