AIS Transponder: DataTerminal::instance
instance()
DataTerminal & DataTerminal::instance () static
Definition at line 31 of file DataTerminal.cpp.
{
  static DataTerminal __instance;
  return __instance;
}
Referenced by mainLoop(), GPS::parseSentence(), printf_serial(), and RXPacketProcessor::processEvent().