AIS Transponder: Receiver::timeSlotStarted
timeSlotStarted()
void Receiver::timeSlotStarted (uint32_t slot) virtual
This is called from the SOTDMA timer interrupt, which is at the same priority as the bit clock. So timeSlotStarted() and onBitClock() cannot preempt each other.
Reimplemented in Transceiver.
Definition at line 150 of file Receiver.cpp.
{
  // This should never be called while transmitting. Transmissions start after the slot boundary and end before the end of it.
  ASSERT(gRadioState == RADIO_RECEIVING);
  mSlotBitNumber = -1;
  mTimeSlot = slot;
  if ( mBitState == BIT_STATE_IN_PACKET )
    return;
  if ( mRXPacket )
    mRXPacket->setSlot(slot);
  if ( mChannel != mNextChannel )
    {
      startReceiving(mNextChannel, false);
    }
}
References ASSERT, BIT_STATE_IN_PACKET, mBitState, mChannel, mNextChannel, mRXPacket, mSlotBitNumber, mTimeSlot, RADIO_RECEIVING, RXPacket::setSlot(), and startReceiving().
Referenced by Transceiver::timeSlotStarted(), and RadioManager::timeSlotStarted().