AIS Transponder: EventPool::deleteEvent
deleteEvent()
void EventPool::deleteEvent (Event * event)
Definition at line 107 of file Events.cpp.
{
  ASSERT_VALID_PTR(event);
  event->reset();
  if ( event->flags )
    mISRPool.put(event);
  else
    mThreadPool.put(event);
}
References ASSERT_VALID_PTR, Event::flags, mISRPool, mThreadPool, and ObjectPool< T >::put().
Referenced by EventQueue::dispatch(), and EventQueue::push().