AIS Transponder: TXScheduler::init
init()
void TXScheduler::init ()
Definition at line 55 of file TXScheduler.cpp.
{
  if ( Configuration::instance().readStationData(mStationData) )
    {
      DBG("Successfully loaded Station Data \r\n");
    }
  else
    {
      DBG("Failed to read Station Data !!!\r\n");
    }
  bool cliBootMode = *(uint32_t*)BOOTMODE_ADDRESS == CLI_FLAG_MAGIC;
  if ( !cliBootMode )
    reportTXStatus();
}
References BOOTMODE_ADDRESS, CLI_FLAG_MAGIC, DBG, Configuration::instance(), mStationData, and reportTXStatus().
Referenced by mainLoop().