AIS Transponder: Configuration::init
init()
void Configuration::init ()
Definition at line 51 of file Configuration.cpp.
{
  bool cliBootMode = *(uint32_t*)BOOTMODE_ADDRESS == CLI_FLAG_MAGIC;
  if ( !cliBootMode )
    {
      reportSystemData();
      reportStationData();
    }
  bsp_read_config_flags(&mFlags);
}
References BOOTMODE_ADDRESS, bsp_read_config_flags(), CLI_FLAG_MAGIC, mFlags, reportStationData(), and reportSystemData().
Referenced by mainLoop().