AIS Transponder: TXScheduler::processEvent
processEvent()
void TXScheduler::processEvent (const Event & event) virtual
Implements EventConsumer.
Definition at line 104 of file TXScheduler.cpp.
{
  switch(e.type)
  {
  case GPS_FIX_EVENT:
    {
      mLastGPSFix = e.gpsFix;
      // We do not schedule transmissions if the ChannelManager is not sure what channels are in use yet
      if ( !ChannelManager::instance().channelsDetermined() )
        return;
      // A class B transponder only transmits when its internal GPS is working, so we tie these to GPS updates.
      if ( !RadioManager::instance().initialized() || mUTC == 0 )
        return;
      if ( !isTXAllowed() )
        return;
      // Using a moving average of SOG to determine transmission rate
      static float alpha = 0.2;
      mAvgSpeed = mAvgSpeed * (1.0 - alpha) + mLastGPSFix.speed * alpha;
      if ( mUTC - mLast18Time > positionReportTimeInterval() )
        {
          queueMessage18(mPositionReportChannel);
          // Our next position report should be on the other channel
          mPositionReportChannel = RadioManager::instance().alternateChannel(mPositionReportChannel);
          mLast18Time = mUTC;
        }
      if ( mUTC - mLast24Time > MSG_24_TX_INTERVAL )
        {
          queueMessage24(mStaticDataChannel);
          // Our next static data report should be on the other channel
          mStaticDataChannel = RadioManager::instance().alternateChannel(mStaticDataChannel);
          mLast24Time = mUTC;
        }
      break;
    }
  case CLOCK_EVENT:
    {
      // This is reliable and independent of GPS update frequency which could change to something other than 1Hz
      if ( mUTC == 0 )
        {
          // Don't start transmitting right away
          mLast18Time = e.clock.utc - MAX_MSG_18_TX_INTERVAL/2;
          mLast24Time = e.clock.utc - MSG_24_TX_INTERVAL/2;
        }
      mUTC = e.clock.utc;
      break;
    }
    break;
  case INTERROGATION_EVENT:
    if ( e.interrogation.messageType == 18 )
      queueMessage18(e.interrogation.channel);
    if ( e.interrogation.messageType == 24 )
      queueMessage24(e.interrogation.channel);
    break;
  default:
    break;
  }
}
References RadioManager::alternateChannel(), Interrogation::channel, Event::clock, CLOCK_EVENT, GPS_FIX_EVENT, Event::gpsFix, ChannelManager::instance(), RadioManager::instance(), Event::interrogation, INTERROGATION_EVENT, isTXAllowed(), mAvgSpeed, MAX_MSG_18_TX_INTERVAL, Interrogation::messageType, mLast18Time, mLast24Time, mLastGPSFix, mPositionReportChannel, MSG_24_TX_INTERVAL, mStaticDataChannel, mUTC, positionReportTimeInterval(), queueMessage18(), queueMessage24(), GPSFix::speed, Event::type, and ClockTick::utc.