AIS Transponder: AISMessage::finalize
finalize()
void AISMessage::finalize (uint8_t * buff, uint16_t & size, TXPacket & packet) protected
Definition at line 134 of file AISMessages.cpp.
{
  // Nothing we send exceeds 256 bits, including preambles and such. 40 bytes is more than enough.
  uint8_t bytes[40];
  // CRC-CCITT calculation
  payloadToBytes(payload, size, bytes);
  uint16_t crc = Utils::crc16(bytes, size/8);
  uint8_t crcL = crc & 0x00ff;
  uint8_t crcH = (crc & 0xff00) >> 8;
  addBits(payload, size, crcL, 8);
  addBits(payload, size, crcH, 8);
  payloadToBytes(payload, size, bytes);
  // Encoding for transmission
  reverseEachByte(payload, size);
  bitStuff(payload, size);
  constructHDLCFrame(payload, size);
  nrziEncode(payload, size, packet);
  packet.pad();
}
References addBits(), bitStuff(), constructHDLCFrame(), Utils::crc16(), nrziEncode(), TXPacket::pad(), payloadToBytes(), and reverseEachByte().
Referenced by AISMessage18::encode(), AISMessage24A::encode(), and AISMessage24B::encode().