AIS Transponder: ObjectPool::get
get()
template<typename T > T * ObjectPool< T >::get () inline
Definition at line 54 of file ObjectPool.hpp.
  {
    T *result = nullptr;
    mQueue.pop(result);
    return result;
  }
References ObjectPool< T >::mQueue, and CircularQueue< T >::pop().
Referenced by EventPool::newEvent(), EventPool::newRXPacket(), and TXPacketPool::newTXPacket().