AIS Transponder: RXPacket::addByte
addByte()
void RXPacket::addByte (uint8_t byte)
Definition at line 167 of file RXPacket.cpp.
{
  // The payload is LSB (inverted MSB bytes). This brings it back into MSB format
  addBit(byte & 0x01);
  addBit(byte & 0x02);
  addBit(byte & 0x04);
  addBit(byte & 0x08);
  addBit(byte & 0x10);
  addBit(byte & 0x20);
  addBit(byte & 0x40);
  addBit(byte & 0x80);
  // Now we can update our CRC in MSB order which is how it was calculated during encoding by the sender ...
  addBitCRC((byte & 0x80) >> 7);
  addBitCRC((byte & 0x40) >> 6);
  addBitCRC((byte & 0x20) >> 5);
  addBitCRC((byte & 0x10) >> 4);
  addBitCRC((byte & 0x08) >> 3);
  addBitCRC((byte & 0x04) >> 2);
  addBitCRC((byte & 0x02) >> 1);
  addBitCRC(byte & 0x01);
}
References addBit(), and addBitCRC().
Referenced by Receiver::addBit().