AIS Transponder: RadioManager::scheduleTransmission
scheduleTransmission()
void RadioManager::scheduleTransmission (TXPacket * p)
Definition at line 208 of file RadioManager.cpp.
{
#if REPORT_TX_SCHEDULING
  Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
#endif
  if ( !mTXQueue.push(packet) )
    {
#if REPORT_TX_SCHEDULING
      if ( e )
        {
          sprintf(e->nmeaBuffer.sentence, "$PAISCHTX,%s,%d*", packet->messageType(), TX_QUEUE_FULL);
          Utils::completeNMEA(e->nmeaBuffer.sentence);
          EventQueue::instance().push(e);
        }
#endif
      TXPacketPool::instance().deleteTXPacket(packet);
    }
#if REPORT_TX_SCHEDULING
  else
    {
      if ( e )
        {
          sprintf(e->nmeaBuffer.sentence, "$PAISCHTX,%s,%d*", packet->messageType(), TX_NO_ERROR);
          Utils::completeNMEA(e->nmeaBuffer.sentence);
          EventQueue::instance().push(e);
        }
    }
#endif
}
References Utils::completeNMEA(), TXPacketPool::deleteTXPacket(), EventQueue::instance(), EventPool::instance(), TXPacketPool::instance(), TXPacket::messageType(), mTXQueue, EventPool::newEvent(), Event::nmeaBuffer, PROPR_NMEA_SENTENCE, EventQueue::push(), CircularQueue< T >::push(), NMEABuffer::sentence, TX_NO_ERROR, and TX_QUEUE_FULL.
Referenced by TXScheduler::queueMessage18(), and TXScheduler::queueMessage24().