AIS Transponder: ObjectPool::put
put()
template<typename T > void ObjectPool< T >::put (T * o) inline
Definition at line 61 of file ObjectPool.hpp.
  {
    mQueue.push(o);
  }
References ObjectPool< T >::mQueue, and CircularQueue< T >::push().
Referenced by EventPool::deleteEvent(), TXPacketPool::deleteTXPacket(), and EventPool::releaseRXPacket().