AIS Transponder: TXPacketPool::deleteTXPacket
deleteTXPacket()
void TXPacketPool::deleteTXPacket (TXPacket * p)
Definition at line 175 of file TXPacket.cpp.
{
  ASSERT(p);
  mPool->put(p);
}
References ASSERT, mPool, and ObjectPool< T >::put().
Referenced by Transceiver::onBitClock(), and RadioManager::scheduleTransmission().