AIS Transponder: RXPacket::bit
bit()
uint8_t RXPacket::bit (uint16_t pos) const
Definition at line 134 of file RXPacket.cpp.
{
  if ( pos < mState.mSize ) {
      uint16_t index = pos / 8;
      uint8_t offset = pos % 8;
      return (mState.mPacket[index] & (1 << offset)) != 0;
  }
  else
    return 0;
}
References mState.
Referenced by addBit(), bits(), messageType(), mmsi(), and repeatIndicator().