AIS Transponder: LEDManager::init
init()
void LEDManager::init ()
Definition at line 42 of file LEDManager.cpp.
{
  if ( TXScheduler::instance().isTXAllowed() )
    bsp_tx_led_on();
  else
    bsp_tx_led_off();
  bsp_set_tick_callback(tickCB);
}
References bsp_set_tick_callback(), bsp_tx_led_off(), bsp_tx_led_on(), TXScheduler::instance(), and tickCB().
Referenced by mainLoop().