AIS Transponder: GPS::onPPS
onPPS()
void GPS::onPPS ()
Definition at line 134 of file GPS.cpp.
{
  // If we don't have time yet, we can't use this
  if ( mUTC == 0 )
    return;
  ++mUTC;     // PPS := advance clock by one second!
  localtime_r (&mUTC, &mTime); // Now we know exactly what UTC second it is, with only microseconds of latency
  if (!mStarted)
    {
      // To keep things simple, we only start the AIS slot timer if we're on an even second (it has a 37.5 Hz frequency)
      mSlotNumber = (mTime.tm_sec % 60) * 2250; // We know what AIS slot number we're in
      if (!(mTime.tm_sec & 0x00000001))
        startTimer ();
    }
  else
    {
      // The timer is on, now let's re-calibrate ...
      if (mTime.tm_sec & 1)
        {
          // On odd seconds, we expect the timer value to be half its period. Just correct it.
          uint32_t nominalTimerValue = mPeriod / 2 - 1;
          //TIM2->CNT = nominalTimerValue;
          bsp_set_sotdma_timer_value(nominalTimerValue);
        }
      else
        {
          // On even seconds, things are a bit more tricky ...
          //uint32_t currentTimerValue = TIM2->CNT;
          uint32_t currentTimerValue = bsp_get_sotdma_timer_value();
          if (currentTimerValue >= mPeriod / 2 - 1)
            {
              // The timer is a little behind, so kick it forward
              //TIM2->CNT = mPeriod - 1;
              bsp_set_sotdma_timer_value(mPeriod - 1);
            }
          else
            {
              // The timer is a little ahead, so pull it back
              //TIM2->CNT = 0;
              bsp_set_sotdma_timer_value(0);
            }
        }
    }
  Event *e = EventPool::instance().newEvent(CLOCK_EVENT);
  if ( e )
    {
      e->clock.utc = mUTC;
      EventQueue::instance ().push(e);
    }
}
References bsp_get_sotdma_timer_value(), bsp_set_sotdma_timer_value(), Event::clock, CLOCK_EVENT, EventQueue::instance(), EventPool::instance(), mPeriod, mSlotNumber, mStarted, mTime, mUTC, EventPool::newEvent(), EventQueue::push(), startTimer(), and ClockTick::utc.
Referenced by gnss1PPSCB().