AIS Transponder: TXScheduler::queueMessage24
queueMessage24()
void TXScheduler::queueMessage24 (VHFChannel channel)
Definition at line 217 of file TXScheduler.cpp.
{
#if REPORT_TX_SCHEDULING
  char sentence[48];
#endif
  // If we don't have valid station data we don't do anything
  if ( mStationData.magic != STATION_DATA_MAGIC )
    return;
  TXPacket *p2 = TXPacketPool::instance().newTXPacket(channel);
  if ( !p2 )
    {
#if REPORT_TX_SCHEDULING
      sprintf(sentence, "$PAISCHTX,24A,%d*", TX_ALLOC_ERROR);
      sendNMEASentence(sentence);
#endif
      return;
    }
  AISMessage24A msg2;
  msg2.encode(mStationData, *p2);
  RadioManager::instance().scheduleTransmission(p2);
  TXPacket *p3 = TXPacketPool::instance().newTXPacket(channel);
  if ( !p3 )
    {
#if REPORT_TX_SCHEDULING
      sprintf(sentence, "$PAISCHTX,24B,%d*", TX_ALLOC_ERROR);
      sendNMEASentence(sentence);
#endif
      return;
    }
  AISMessage24B msg3;
  msg3.encode(mStationData, *p3);
  RadioManager::instance().scheduleTransmission(p3);
}
References AISMessage24A::encode(), AISMessage24B::encode(), RadioManager::instance(), TXPacketPool::instance(), StationData::magic, mStationData, TXPacketPool::newTXPacket(), RadioManager::scheduleTransmission(), sendNMEASentence(), STATION_DATA_MAGIC, and TX_ALLOC_ERROR.
Referenced by CommandProcessor::processCommand(), and processEvent().