AIS Transponder: NoiseFloorDetector::instance
instance()
NoiseFloorDetector & NoiseFloorDetector::instance () static
Definition at line 29 of file NoiseFloorDetector.cpp.
{
  static NoiseFloorDetector __instance;
  return __instance;
}
Referenced by RadioManager::init(), Transceiver::onBitClock(), and Receiver::reportRSSI().