AIS Transponder: Receiver::pushPacket
pushPacket()
void Receiver::pushPacket () protected
We're out of resources so just keep using the existing packet. If this happens, the most logical outcome is a watchdog reset because something has blocked the main task and the pool is not getting replenished
Definition at line 272 of file Receiver.cpp.
{
  Event *p = EventPool::instance().newEvent(AIS_PACKET_EVENT);
  ASSERT_VALID_PTR(p);
  if ( p )
    {
      //bsp_signal_high();
      p->rxPacket = mRXPacket;
      if ( !EventQueue::instance().push(p) )
        {
          // This has never happened
        }
      //bsp_signal_low();
      mRXPacket = EventPool::instance().newRXPacket();
      if ( !mRXPacket )
        {
          // This has never happened
        }
    }
  else
    {
      // This has never happened
      mRXPacket->reset();
    }
}
References AIS_PACKET_EVENT, ASSERT_VALID_PTR, EventQueue::instance(), EventPool::instance(), mRXPacket, EventPool::newEvent(), EventPool::newRXPacket(), RXPacket::reset(), and Event::rxPacket.
Referenced by processNRZIBit().