AIS Transponder: Configuration::reportSystemData
reportSystemData()
void Configuration::reportSystemData ()
Definition at line 134 of file Configuration.cpp.
{
  Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
  if ( !e )
    return;
  sprintf(e->nmeaBuffer.sentence, "$PAISYS,%s,%s,%s,%s,%s,%d*", hwRev(), FW_REV, serNum(), mcuType(),
      breakoutType(), isBootloaderPresent());
  Utils::completeNMEA(e->nmeaBuffer.sentence);
  EventQueue::instance().push(e);
}
References breakoutType(), Utils::completeNMEA(), FW_REV, hwRev(), EventQueue::instance(), EventPool::instance(), isBootloaderPresent(), mcuType(), EventPool::newEvent(), Event::nmeaBuffer, PROPR_NMEA_SENTENCE, EventQueue::push(), NMEABuffer::sentence, and serNum().
Referenced by init(), and CommandProcessor::processCommand().