AIS Transponder: RXPacket::reset
reset()
void RXPacket::reset ()
Definition at line 82 of file RXPacket.cpp.
{
  mState = {{0}, 0, 0xffff, 0, 0, 0, 0xffffffff, CH_18, 0};
#if 0
  mType = 0;
  mRI = 0;
  mMMSI = 0;
  mSize = 0;
  mCRC = 0xffff;
  mSlot = 0xffffffff;
  mRSSI = 0;
  memset(mPacket, 0, sizeof mPacket);
#endif
}
References CH_18, mCRC, mMMSI, mPacket, mRI, mRSSI, mSize, mSlot, mState, and mType.
Referenced by Receiver::pushPacket(), Receiver::resetBitScanner(), and RXPacket().