AIS Transponder: NoiseFloorDetector::dump
dump()
void NoiseFloorDetector::dump () private
Definition at line 101 of file NoiseFloorDetector.cpp.
{
  Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
  if ( !e )
    return;
  sprintf(e->nmeaBuffer.sentence, "$PAINF,A,0x%.2x*", mChannelACurrent);
  Utils::completeNMEA(e->nmeaBuffer.sentence);
  EventQueue::instance().push(e);
  e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
  if ( !e )
    return;
  sprintf(e->nmeaBuffer.sentence, "$PAINF,B,0x%.2x*", mChannelBCurrent);
  Utils::completeNMEA(e->nmeaBuffer.sentence);
  EventQueue::instance().push(e);
}
References Utils::completeNMEA(), EventQueue::instance(), EventPool::instance(), mChannelACurrent, mChannelBCurrent, EventPool::newEvent(), Event::nmeaBuffer, PROPR_NMEA_SENTENCE, EventQueue::push(), and NMEABuffer::sentence.
Referenced by processEvent().