AIS Transponder: RadioManager::reportError
reportError()
void RadioManager::reportError (int chipId) private
Definition at line 123 of file RadioManager.cpp.
{
  Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
  if ( !e )
    return;
  sprintf(e->nmeaBuffer.sentence, "$PAIERR,RFIC,%d*", chipId);
  Utils::completeNMEA(e->nmeaBuffer.sentence);
  EventQueue::instance().push(e);
}
References Utils::completeNMEA(), EventQueue::instance(), EventPool::instance(), EventPool::newEvent(), Event::nmeaBuffer, PROPR_NMEA_SENTENCE, EventQueue::push(), and NMEABuffer::sentence.
Referenced by init().