AIS Transponder: TXPacket::channel
channel()
VHFChannel TXPacket::channel ()
Definition at line 91 of file TXPacket.cpp.
{
  return mChannel;
}
References mChannel.
Referenced by configure(), configureForTesting(), Transceiver::onBitClock(), RadioManager::processEvent(), Transceiver::reportTXEvent(), Transceiver::startTransmitting(), and Transceiver::timeSlotStarted().