AIS Transponder: Transceiver::configure
configure()
void Transceiver::configure () protected virtual
We need maximum digital ramp control to reduce spurs. It's only about 200us, which is less than the ramp-up bits in the TX packet, but it sure helped!
Reimplemented from RFIC.
Definition at line 44 of file Transceiver.cpp.
{
  Receiver::configure();
  // Anything transmitter specific goes here
  SET_PROPERTY_PARAMS p;
  p.Group = 0x20;
  p.NumProperties = 1;
  p.StartProperty = 0x00;
  p.Data[0] = 0x20 | 0x08 | 0x03; // Synchronous direct mode from GPIO 1 with 2GFSK modulation
  sendCmd(SET_PROPERTY, &p, 4, NULL, 0);
  p.Group = 0x22;
  p.NumProperties = 1;
  p.StartProperty = 0x06;
  p.Data[0] = 0xff;
  sendCmd(SET_PROPERTY, &p, 6, NULL, 0);
  /*
   * AIS uses a slightly different Gaussian shape than default GMSK in the Si4463.
   * This sets the TX filter coefficients for a BT of 0.4 as per ITU specification.
   *
   * https://www.silabs.com/community/wireless/proprietary/forum.topic.html/si4463_gmsk_spectrum-ojkN
   */
  uint8_t data[] = { 0x52, 0x4f, 0x45, 0x37, 0x28, 0x1a, 0x10, 0x09, 0x04 };
  p.Group = 0x22;
  p.NumProperties = 9;
  p.StartProperty = 0x0f;
  memcpy(p.Data, data, sizeof data);
  sendCmd(SET_PROPERTY, &p, 12, NULL, 0);
  // These resulted from characterization with default BOM
  pa_params pwr;
  switch(mPartNumber)
  {
  case 0x4463:
    pwr.pa_mode = 0x48;
    pwr.pa_level = 0x10;
    pwr.pa_bias_clkduty = 0x00;
    break;
  case 0x4467:
    pwr.pa_mode = 0x48;
    pwr.pa_level = 0x1C;
    pwr.pa_bias_clkduty = 0x00;
    break;
  default:
    pwr.pa_mode = 0x48;
    pwr.pa_level = 0x1C;
    pwr.pa_bias_clkduty = 0x00;
    break;
  }
  setTXPower(pwr);
}
References RFIC::configure(), SET_PROPERTY_PARAMS::Data, SET_PROPERTY_PARAMS::Group, RFIC::mPartNumber, SET_PROPERTY_PARAMS::NumProperties, pa_params::pa_bias_clkduty, pa_params::pa_level, pa_params::pa_mode, RFIC::sendCmd(), SET_PROPERTY, setTXPower(), and SET_PROPERTY_PARAMS::StartProperty.