AIS Transponder: EventQueue::dispatch
dispatch()
void EventQueue::dispatch ()
Definition at line 79 of file EventQueue.cpp.
{
  Event *e = nullptr;
  while (mISRQueue.pop(e))
    {
      for ( map<EventConsumer*, uint32_t>::iterator c = mConsumers.begin(); c != mConsumers.end(); ++c )
        {
          if ( c->second & e->type )
            {
              c->first->processEvent(*e);
            }
        }
      EventPool::instance().deleteEvent(e);
    }
  while (mTaskQueue.pop(e))
    {
      for ( map<EventConsumer*, uint32_t>::iterator c = mConsumers.begin(); c != mConsumers.end(); ++c )
        {
          if ( c->second & e->type )
            {
              c->first->processEvent(*e);
            }
        }
      EventPool::instance().deleteEvent(e);
    }
}
References EventPool::deleteEvent(), EventPool::instance(), mConsumers, mISRQueue, mTaskQueue, CircularQueue< T >::pop(), and Event::type.
Referenced by mainLoop().