AIS Transponder: Configuration::writeStationData
writeStationData()
bool Configuration::writeStationData (const StationData & data)
Definition at line 230 of file Configuration.cpp.
{
  bsp_write_station_data(data);
  reportStationData();
  return true;
}
References bsp_write_station_data(), and reportStationData().
Referenced by CommandProcessor::processCommand().