AIS Transponder: AISMessage24B::encode
encode()
void AISMessage24B::encode (const StationData & data, TXPacket & packet) virtual
Encodes AIS message 24B into a transmit packet.
Parameters
data The station data to be included in the message.
packet The TXPacket to store the encoded message.
Reimplemented from AISMessage.
Definition at line 435 of file AISMessages.cpp.
{
  AISMessage::encode(station, packet);
  packet.setMessageType("24B");
  uint8_t payload[MAX_AIS_TX_PACKET_SIZE];
  uint16_t size = 0;
  uint32_t value;
  value = mType;
  addBits(payload, size, value, 6);   // Message type
  value = mRI;
  addBits(payload, size, value, 2);   // Repeat Indicator
  value = mMMSI;
  addBits(payload, size, value, 30);  // MMSI
  value = 1;
  addBits(payload, size, value, 2);   // Part number (1 for 24B)
  value = station.type;
  addBits(payload, size, value, 8);   // Type of ship
  addString(payload, size, "", 7);    // Vendor information
  addString(payload, size, station.callsign, 7);  // Call sign
  if ( station.len == 0 || station.beam == 0 )
    {
      value = 0;
    }
  else
    {
      uint16_t A,B,C,D;
      C = station.portOffset;
      D = station.beam - C;
      A = station.bowOffset;
      B = station.len - A;
      if ( D > 63 )
        D = 63;
      if ( C > 63 )
        C = 63;
      if ( B > 511 )
        B = 511;
      if ( A > 511 )
        A = 511;
      value = D | (C << 6) | (B << 12) | (A << 21);
    }
  addBits(payload, size, value, 30);  // Dimension information
  value = 1;
  addBits(payload, size, value, 4);   // We are using GPS only
  value = 0;
  addBits(payload, size, value, 2);   // Spare bits
  finalize(payload, size, packet);
}
References AISMessage::addBits(), AISMessage::addString(), StationData::beam, StationData::bowOffset, StationData::callsign, AISMessage::encode(), AISMessage::finalize(), StationData::len, MAX_AIS_TX_PACKET_SIZE, AISMessage::mMMSI, AISMessage::mRI, AISMessage::mType, StationData::portOffset, TXPacket::setMessageType(), and StationData::type.
Referenced by TXScheduler::queueMessage24().