AIS Transponder: GPS::init
init()
void GPS::init ()
Definition at line 86 of file GPS.cpp.
{
  bsp_set_gnss_input_callback(gnssInputCB);
  bsp_set_gnss_1pps_callback(gnss1PPSCB);
  bsp_set_gnss_sotdma_timer_callback(gnssSOTDMACB);
}
References bsp_set_gnss_1pps_callback(), bsp_set_gnss_input_callback(), bsp_set_gnss_sotdma_timer_callback(), gnss1PPSCB(), gnssInputCB(), and gnssSOTDMACB().
Referenced by mainLoop().