AIS Transponder: Utils::completeNMEA
completeNMEA()
void Utils::completeNMEA (char * buff) static
Definition at line 206 of file Utils.cpp.
{
  uint8_t p = 1;
  uint8_t crc = buff[p++];
  while ( buff[p] != '*' )
    crc ^= buff[p++];
  sprintf(buff+p+1, "%.2X\r\n", crc);
}
Referenced by NoiseFloorDetector::dump(), Transceiver::onBitClock(), RadioManager::reportError(), Configuration::reportStationData(), Configuration::reportSystemData(), Transceiver::reportTXEvent(), TXScheduler::reportTXStatus(), Configuration::reportXOTrimValue(), RadioManager::scheduleTransmission(), and TXScheduler::sendNMEASentence().