AIS Transponder: Receiver::resetBitScanner
resetBitScanner()
void Receiver::resetBitScanner () protected
Definition at line 99 of file Receiver.cpp.
{
  mBitWindow = 0;
  mBitCount = 0;
  mOneBitCount = 0;
  mLastNRZIBit = 0xff;
  mRXByte = 0;
  mBitState = BIT_STATE_PREAMBLE_SYNC;
  if ( mRXPacket )
    mRXPacket->reset();
}
References BIT_STATE_PREAMBLE_SYNC, mBitCount, mBitState, mBitWindow, mLastNRZIBit, mOneBitCount, mRXByte, mRXPacket, and RXPacket::reset().
Referenced by init(), and startReceiving().