AIS Transponder: Transceiver::transmitCW
transmitCW()
void Transceiver::transmitCW (VHFChannel channel)
Definition at line 116 of file Transceiver.cpp.
{
  startReceiving(channel, false);
  configureGPIOsForTX();
  SET_PROPERTY_PARAMS p;
  p.Group = 0x20;
  p.NumProperties = 1;
  p.StartProperty = 0x00;
  p.Data[0] = 0x08;
  sendCmd (SET_PROPERTY, &p, 4, NULL, 0);
  TX_OPTIONS options;
  options.channel = AIS_CHANNELS[channel].ordinal;
  options.condition = 8 << 4;
  options.tx_len = 0;
  options.tx_delay = 0;
  options.repeats = 0;
  sendCmd (START_TX, &options, sizeof options, NULL, 0);
}
References TX_OPTIONS::channel, Receiver::channel(), TX_OPTIONS::condition, configureGPIOsForTX(), SET_PROPERTY_PARAMS::Data, SET_PROPERTY_PARAMS::Group, SET_PROPERTY_PARAMS::NumProperties, TX_OPTIONS::repeats, RFIC::sendCmd(), SET_PROPERTY, START_TX, SET_PROPERTY_PARAMS::StartProperty, startReceiving(), TX_OPTIONS::tx_delay, and TX_OPTIONS::tx_len.
Referenced by RadioManager::transmitCW().