AIS Transponder: Transceiver::onBitClock
onBitClock()
void Transceiver::onBitClock () virtual
This method is called in interrupt context
As of September 2020, the digital ramp-down of the Si4463 is broken and not in the latest firmware patch either, so this is a good alternative.
The packet has 2-3 ramp down bits, so when it tells us it's reached them, we ramp the bias voltage down by means of the RC delay circuit. This really helped clean up spurs.
Reimplemented from Receiver.
Definition at line 187 of file Transceiver.cpp.
{
  if ( gRadioState == RADIO_RECEIVING )
    {
      Receiver::onBitClock();
      /*
          We start transmitting a packet if:
            - We have a TX packet assigned
            - Transmission is enabled
            - We are at bit CCA_SLOT_BIT+1 (after obtaining an RSSI level)
            - The TX packet's transmission channel is our current listening channel
            - The RSSI is within 6dB of the noise floor for this channel
            - It's been at least MIN_TX_INTERVAL seconds since our last transmission
       */
      if ( !mTXPacket )
        return;
      if ( mTXPacket->isTestPacket() )
        {
          // Test packets are sent immediately. Presumably, we're firing into a dummy load ;)
          startTransmitting();
        }
      else if ( !TXScheduler::instance().isTXAllowed() )
        {
          // Transmission has been disabled since scheduling, so don't transmit!
          TXPacketPool::instance().deleteTXPacket(mTXPacket);
          mTXPacket = NULL;
        }
      else if ( mUTC && mUTC - mTXPacket->timestamp() >= MIN_MSG_18_TX_INTERVAL )
        {
          // The packet is way too old. Discard it.
          DBG("Packet is too old. Discarding!\r\n");
#if REPORT_TX_SCHEDULING
          Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
          if ( e )
            {
              sprintf(e->nmeaBuffer.sentence, "$PAISCHTX,%s,%d*", mTXPacket->messageType(), TX_PACKET_TOO_OLD);
              Utils::completeNMEA(e->nmeaBuffer.sentence);
              EventQueue::instance().push(e);
            }
#endif
          TXPacketPool::instance().deleteTXPacket(mTXPacket);
          mTXPacket = NULL;
        }
      else if ( mUTC - mLastTXTime < MIN_TX_INTERVAL )
        {
          DBG("It's not time to transmit yet\r\n");
          // It's not time to transmit yet
          return;
        }
      else if ( mUTC && mSlotBitNumber == CCA_SLOT_BIT && mTXPacket->channel() == mChannel )
        {
          // It has already been sampled during Receiver::onBitClock();
          int rssi = mRXPacket->rssi();
          int nf = NoiseFloorDetector::instance().getNoiseFloor(AIS_CHANNELS[mChannel].designation);
          if ( rssi <= nf + TX_CCA_HEADROOM )
            {
              startTransmitting();
            }
        }
    }
  else if ( mTXPacket )
    {
      if ( mTXPacket->eof() )
        {
          mLastTXTime = mUTC;
          startReceiving(mChannel, true);
          gRadioState = RADIO_RECEIVING;
          reportTXEvent();
          TXPacketPool::instance().deleteTXPacket(mTXPacket);
          mTXPacket = NULL;
        }
      else
        {
          uint8_t bit = mTXPacket->nextBit();
          if ( bit )
            HAL_GPIO_WritePin(mDataPort, mDataPin, GPIO_PIN_SET);
          else
            HAL_GPIO_WritePin(mDataPort, mDataPin, GPIO_PIN_RESET);
          if ( mTXPacket->canRampDown() )
            HAL_GPIO_WritePin(PA_BIAS_PORT, PA_BIAS_PIN, GPIO_PIN_RESET);
        }
    }
  else
    {
      // We're transmitting carrier wave, do nothing. This is only done during XO trimming.
    }
}
References TXPacket::canRampDown(), CCA_SLOT_BIT, TXPacket::channel(), Utils::completeNMEA(), DBG, TXPacketPool::deleteTXPacket(), TXPacket::eof(), NoiseFloorDetector::getNoiseFloor(), EventQueue::instance(), EventPool::instance(), NoiseFloorDetector::instance(), TXPacketPool::instance(), TXScheduler::instance(), TXPacket::isTestPacket(), Receiver::mChannel, RFIC::mDataPin, RFIC::mDataPort, TXPacket::messageType(), MIN_MSG_18_TX_INTERVAL, MIN_TX_INTERVAL, mLastTXTime, Receiver::mRXPacket, Receiver::mSlotBitNumber, mTXPacket, mUTC, EventPool::newEvent(), TXPacket::nextBit(), Event::nmeaBuffer, Receiver::onBitClock(), PA_BIAS_PIN, PA_BIAS_PORT, PROPR_NMEA_SENTENCE, EventQueue::push(), RADIO_RECEIVING, reportTXEvent(), RXPacket::rssi(), NMEABuffer::sentence, startReceiving(), startTransmitting(), TXPacket::timestamp(), TX_CCA_HEADROOM, and TX_PACKET_TOO_OLD.
Referenced by RadioManager::onBitClock().