AIS Transponder: TXPacketPool::newTXPacket
newTXPacket()
TXPacket * TXPacketPool::newTXPacket (VHFChannel channel)
Definition at line 164 of file TXPacket.cpp.
{
  TXPacket *p = mPool->get();
  if ( !p )
    return p;
  p->reset();
  p->configure(channel);
  return p;
}
References TXPacket::configure(), ObjectPool< T >::get(), mPool, and TXPacket::reset().
Referenced by fireTestPacket(), TXScheduler::queueMessage18(), and TXScheduler::queueMessage24().