AIS Transponder: Transceiver::assignTXPacket
assignTXPacket()
void Transceiver::assignTXPacket (TXPacket * p)
Definition at line 172 of file Transceiver.cpp.
{
  ASSERT(!mTXPacket);
  mTXPacket = p;
  mTXPacket->setTimestamp(mUTC);
}
References ASSERT, mTXPacket, mUTC, and TXPacket::setTimestamp().
Referenced by RadioManager::processEvent(), and RadioManager::sendTestPacketNow().