AIS Transponder: Receiver::startReceiving
startReceiving()
void Receiver::startReceiving (VHFChannel channel, bool reconfigGPIOs) virtual
Reimplemented in Transceiver.
Definition at line 63 of file Receiver.cpp.
{
  mChannel = channel;
  mNextChannel = channel;
  startListening(mChannel, reconfigGPIOs);
  resetBitScanner();
}
References channel(), mChannel, mNextChannel, resetBitScanner(), and startListening().
Referenced by onBitClock(), RadioManager::start(), Transceiver::startReceiving(), and timeSlotStarted().