AIS Transponder: AISMessage15::decode
decode()
bool AISMessage15::decode (const RXPacket & packet) virtual
Decodes a received packet containing AIS message 15.
Parameters
packet The RXPacket containing the received AIS message 15 data.
Returns
True if decoding was successful, false otherwise.
Reimplemented from AISMessage.
Definition at line 259 of file AISMessages.cpp.
{
  mType = packet.messageType();
  mRI = packet.repeatIndicator();
  mMMSI = packet.mmsi();
  uint8_t bit = 40;
  // A message 15 has up to 3 targets
  for ( uint8_t i = 0; i < 3; ++i ) {
      if ( bit >= packet.size()-16 )
        break;
      targets[i].mmsi = packet.bits(bit, 30);
      bit += 30;
      targets[i].messageType = (uint8_t)packet.bits(bit, 6);
      bit += 6;
      // Ignore slot offset plus 2 spare bits per record
      bit += 14;
  }
  return true; // Would we ever return false?
}
References RXPacket::bits(), AISMessage15::InterrogationTarget::messageType, RXPacket::messageType(), AISMessage::mMMSI, AISMessage15::InterrogationTarget::mmsi, RXPacket::mmsi(), AISMessage::mRI, AISMessage::mType, RXPacket::repeatIndicator(), RXPacket::size(), and targets.
Referenced by RXPacketProcessor::processEvent().