AIS Transponder: GPS::parseSentence
parseSentence()
void GPS::parseSentence (const char * buff) private
Definition at line 215 of file GPS.cpp.
{
  NMEASentence sentence (buff);
#ifdef MULTIPLEXED_OUTPUT
  DataTerminal::instance ().write ("NMEA", buff);
#else
  DataTerminal::instance().write(buff);
#endif
  if (sentence.code ().find ("RMC") == 2)
    {
      const vector<string> &fields = sentence.fields ();
      /*
       * Sometimes the GPS indicates errors with sentences like
       * $GPRMC,1420$0*74\r\n
       * Although the sentence structure is valid, its content is not what we expect.
       *
       * TODO: Should we consider the GPS non-functioning at this point and thus prevent transmission until it recovers?
       */
      if (fields.size () < 10)
        return;
      // GPS updates arrive even with no time or fix information, so ignore them if that's the case
      if (fields[1].length () < 6 || fields[9].length () < 6)
        {
          // TODO: A loss of fix while the SOTDMA timer is active, MUST stop the timer
          bsp_gps_led_off();
          return;
        }
      // This is the time that corresponds to the previous PPS
      const string &timestr = fields[1].substr (0, 6);
      const string &datestr = fields[9].substr (0, 6);
      mTime.tm_hour = Utils::toInt (timestr.substr (0, 2));
      mTime.tm_min = Utils::toInt (timestr.substr (2, 2));
      mTime.tm_sec = Utils::toInt (timestr.substr (4, 2));
      mTime.tm_mday = Utils::toInt (datestr.substr (0, 2));
      mTime.tm_mon = Utils::toInt (datestr.substr (2, 2)) - 1; // Month is 0-based
      mTime.tm_year = 100 + Utils::toInt (datestr.substr (4, 2)); // Year is 1900-based
      mUTC = mktime (&mTime);
      // Do we have a fix?
      if (mUTC && sentence.fields()[3].length() > 0 && sentence.fields()[5].length() > 0)
        {
          bsp_gps_led_on();
          mLat = Utils::latitudeFromNMEA (sentence.fields()[3], sentence.fields()[4]);
          mLng = Utils::longitudeFromNMEA (sentence.fields()[5], sentence.fields()[6]);
          mSpeed = atof(sentence.fields()[7].c_str());
          mCOG = atof(sentence.fields()[8].c_str());
          Event *e = EventPool::instance().newEvent(GPS_FIX_EVENT);
          if ( e )
            {
              Event &event = *e;
              event.gpsFix.utc = mUTC;
              event.gpsFix.lat = mLat;
              event.gpsFix.lng = mLng;
              event.gpsFix.speed = mSpeed;
              event.gpsFix.cog = mCOG;
              EventQueue::instance().push (e);
            }
        }
      else
        {
          bsp_gps_led_off();
        }
    }
}
References bsp_gps_led_off(), bsp_gps_led_on(), NMEASentence::code(), NMEASentence::fields(), GPS_FIX_EVENT, Event::gpsFix, DataTerminal::instance(), EventQueue::instance(), EventPool::instance(), Utils::latitudeFromNMEA(), Utils::longitudeFromNMEA(), mCOG, mLat, mLng, mSpeed, mTime, mUTC, EventPool::newEvent(), EventQueue::push(), Utils::toInt(), GPSFix::utc, and DataTerminal::write().
Referenced by processLine().