AIS Transponder: EventQueue::addObserver
addObserver()
void EventQueue::addObserver (EventConsumer * c, uint32_t eventMask)
Definition at line 65 of file EventQueue.cpp.
{
  mConsumers[c] = eventMask;
}
References mConsumers.
Referenced by ChannelManager::ChannelManager(), CommandProcessor::CommandProcessor(), DataTerminal::DataTerminal(), GPS::GPS(), NoiseFloorDetector::NoiseFloorDetector(), RadioManager::RadioManager(), RXPacketProcessor::RXPacketProcessor(), Transceiver::Transceiver(), and TXScheduler::TXScheduler().