AIS Transponder: Receiver::channel
channel()
VHFChannel Receiver::channel ()
Definition at line 51 of file Receiver.cpp.
{
  return mChannel;
}
References mChannel.
Referenced by RadioManager::processEvent(), reportRSSI(), startListening(), startReceiving(), Transceiver::startReceiving(), switchToChannel(), and Transceiver::transmitCW().