AIS Transponder: RadioManager::init
init()
void RadioManager::init ()
Definition at line 51 of file RadioManager.cpp.
{
  NoiseFloorDetector::instance();
  mTransceiverIC = new Transceiver(SDN1_PORT, SDN1_PIN,
      CS1_PORT, CS1_PIN,
      TRX_IC_DATA_PORT, TRX_IC_DATA_PIN,
      TRX_IC_CLK_PORT, TRX_IC_CLK_PIN, 0);
  if ( mTransceiverIC->isResponsive() )
    {
      mTransceiverIC->init();
    }
  else
    {
      reportError(1);
    }
  mReceiverIC = new Receiver(SDN2_PORT, SDN2_PIN,
      CS2_PORT, CS2_PIN,
      RX_IC_DATA_PORT, RX_IC_DATA_PIN,
      RX_IC_CLK_PORT, RX_IC_CLK_PIN, 1);
  if ( mReceiverIC->isResponsive() )
    {
      mReceiverIC->init();
    }
  else
    {
      reportError(2);
    }
  if ( mReceiverIC->isResponsive() && mTransceiverIC->isResponsive() )
    mInitializing = false;
}
References CS1_PIN, CS1_PORT, CS2_PIN, CS2_PORT, Receiver::init(), NoiseFloorDetector::instance(), RFIC::isResponsive(), mInitializing, mReceiverIC, mTransceiverIC, reportError(), RX_IC_CLK_PIN, RX_IC_CLK_PORT, RX_IC_DATA_PIN, RX_IC_DATA_PORT, SDN1_PIN, SDN1_PORT, SDN2_PIN, SDN2_PORT, TRX_IC_CLK_PIN, TRX_IC_CLK_PORT, TRX_IC_DATA_PIN, and TRX_IC_DATA_PORT.
Referenced by mainLoop().