AIS Transponder: RFIC::spiOn
spiOn()
void RFIC::spiOn () inline private
Definition at line 65 of file RFIC.cpp.
{
  HAL_GPIO_WritePin(mCSPort, mCSPin, GPIO_PIN_RESET);
}
References mCSPin, and mCSPort.
Referenced by readSPIResponse(), sendCmd(), and sendCmdNoWait().