AIS Transponder: RXPacket::bits
bits()
uint32_t RXPacket::bits (uint16_t pos, uint8_t count) const
Definition at line 146 of file RXPacket.cpp.
{
  ASSERT(count <= 32);
  uint32_t result = 0;
  for ( uint16_t i = pos; i < pos+count; ++i ) {
      result <<= 1;
      result |= bit(i);
  }
  return result;
}
References ASSERT, and bit().
Referenced by AISMessage15::decode(), and NMEAEncoder::encode().