AIS Transponder: EventQueue::instance
instance()
EventQueue & EventQueue::instance () static
Definition at line 28 of file EventQueue.cpp.
{
  static EventQueue __instance;
  return __instance;
}
Referenced by ChannelManager::ChannelManager(), CommandProcessor::CommandProcessor(), DataTerminal::DataTerminal(), NoiseFloorDetector::dump(), GPS::GPS(), mainLoop(), NoiseFloorDetector::NoiseFloorDetector(), Transceiver::onBitClock(), GPS::onPPS(), GPS::onRX(), GPS::parseSentence(), printf_serial(), RXPacketProcessor::processEvent(), Receiver::pushPacket(), RadioManager::RadioManager(), RadioManager::reportError(), Configuration::reportStationData(), Configuration::reportSystemData(), Transceiver::reportTXEvent(), TXScheduler::reportTXStatus(), Configuration::reportXOTrimValue(), RXPacketProcessor::RXPacketProcessor(), RadioManager::scheduleTransmission(), TXScheduler::sendNMEASentence(), termInputCB(), Transceiver::Transceiver(), TXScheduler::TXScheduler(), and RXPacketProcessor::~RXPacketProcessor().