AIS Transponder: Configuration::reportStationData
reportStationData()
void Configuration::reportStationData ()
Definition at line 147 of file Configuration.cpp.
{
  StationData d;
  if ( !readStationData(d) )
    memset(&d, 0, sizeof d);
  Event *e = EventPool::instance().newEvent(PROPR_NMEA_SENTENCE);
  if ( !e )
    return;
  sprintf(e->nmeaBuffer.sentence,
      "$PAISTN,%lu,%s,%s,%d,%d,%d,%d,%d*",
      d.mmsi,
      d.name,
      d.callsign,
      d.type,
      d.len,
      d.beam,
      d.portOffset,
      d.bowOffset);
  Utils::completeNMEA(e->nmeaBuffer.sentence);
  EventQueue::instance().push(e);
}
References StationData::beam, StationData::bowOffset, StationData::callsign, Utils::completeNMEA(), EventQueue::instance(), EventPool::instance(), StationData::len, StationData::mmsi, StationData::name, EventPool::newEvent(), Event::nmeaBuffer, StationData::portOffset, PROPR_NMEA_SENTENCE, EventQueue::push(), readStationData(), NMEABuffer::sentence, and StationData::type.
Referenced by init(), CommandProcessor::processCommand(), and writeStationData().