AIS Transponder: EventPool::instance
instance()
EventPool & EventPool::instance () static
Definition at line 55 of file Events.cpp.
{
  static EventPool __instance;
  return __instance;
}
Referenced by EventQueue::dispatch(), NoiseFloorDetector::dump(), mainLoop(), Receiver::onBitClock(), Transceiver::onBitClock(), GPS::onPPS(), GPS::onRX(), GPS::parseSentence(), printf_serial(), EventQueue::push(), Receiver::pushPacket(), Receiver::Receiver(), RadioManager::reportError(), Configuration::reportStationData(), Configuration::reportSystemData(), Transceiver::reportTXEvent(), TXScheduler::reportTXStatus(), Configuration::reportXOTrimValue(), Event::reset(), RadioManager::scheduleTransmission(), TXScheduler::sendNMEASentence(), and termInputCB().