AIS Transponder: CommandProcessor::processCommand
processCommand()
void CommandProcessor::processCommand (const char * cmd) private
Processes a given command string.
Parameters
cmd The command string to be processed.
Parses and executes the provided command string.
Definition at line 85 of file CommandProcessor.cpp.
{
  string s(buff);
  Utils::trim(s);
  if ( s.find("station ") == 0 )
    {
      /*
       * The station command format is:
       * station mmsi,name,callsign,type,len,beam,portoffset,bowoffset
       */
      StationData station;
      string params = s.substr(8);
      if (params.empty())
        return;
      vector<string> tokens;
      Utils::tokenize(params, ',', tokens);
      if ( tokens.size() < 8 )
        return;
      memset(&station, 0, sizeof station);
      station.mmsi = Utils::toInt(tokens[0]);
      strlcpy(station.name, tokens[1].c_str(), sizeof station.name);
      strlcpy(station.callsign, tokens[2].c_str(), sizeof station.callsign);
      int type = (VesselType)Utils::toInt(tokens[3]);
      if ( type == 30 || type == 34 || type == 36 || type == 37 )
        station.type = (VesselType)type;
      station.len = Utils::toInt(tokens[4]);
      station.beam = Utils::toInt(tokens[5]);
      station.portOffset = Utils::toInt(tokens[6]);
      station.bowOffset = Utils::toInt(tokens[7]);
      station.magic = STATION_DATA_MAGIC;
      Configuration::instance().writeStationData(station);
    }
  else if ( s.find("station?") == 0 )
    {
      Configuration::instance().reportStationData();
    }
  else if ( s.find("sys?") == 0 )
    {
      Configuration::instance().reportSystemData();
    }
  else if ( s.find("dfu") == 0 )
    {
      jumpToBootloader();
    }
  else if ( s.find("erase station") == 0 )
    {
      Configuration::instance().eraseStationData();
      Configuration::instance().reportStationData();
    }
  else if ( s.find("factory reset") == 0 )
    {
      Configuration::instance().factoryReset();
      Configuration::instance().reportStationData();
    }
  else if ( s.find("tx test") == 0 )
    {
      fireTestPacket();
    }
  else if ( s.find("tx on") == 0 )
    {
      Configuration::instance().enableTX();
      TXScheduler::instance().reportTXStatus();
    }
  else if ( s.find("tx off") == 0 )
    {
      Configuration::instance().disableTX();
      TXScheduler::instance().reportTXStatus();
    }
  else if ( s.find("tx?") == 0 )
    {
      TXScheduler::instance().reportTXStatus();
    }
  else if ( s.find("txcw a") == 0 )
    {
      RadioManager::instance().transmitCW(CH_87);
    }
  else if ( s.find("txcw b") == 0 )
    {
      RadioManager::instance().transmitCW(CH_88);
    }
  else if ( s.find("stoptx") == 0 )
    {
      RadioManager::instance().stopTX();
    }
  else if (s.find("reboot") == 0 )
    {
      bsp_reboot();
    }
  else if ( s.find("cli") == 0 )
    {
      enterCLIMode();
    }
  else if ( s.find("gps off") == 0 )
    {
      bsp_gnss_off();
    }
  else if ( s.find("gps on") == 0 )
    {
      bsp_gnss_on();
    }
  else if ( s.find("msg24") == 0 )
    {
      TXScheduler::instance().queueMessage24(CH_87);
    }
#if OTP_DATA
  else if ( s.find("otp?") == 0 )
    {
      dumpOTPData();
    }
  else if ( s.find("otp ") == 0 )
    {
      writeOTPData(s);
    }
#endif
  else if ( s.find("xotrim ") == 0 )
    {
      uint8_t value = Utils::toInt(s.substr(7));
      RadioManager::instance().setXOTrimValue(value);
      Configuration::instance().setXOTrimValue(value);
    }
  else if ( s.find("xotrim?") == 0 )
    {
      Configuration::instance().reportXOTrimValue();
    }
}
References StationData::beam, StationData::bowOffset, bsp_gnss_off(), bsp_gnss_on(), bsp_reboot(), StationData::callsign, CH_87, CH_88, Configuration::disableTX(), dumpOTPData(), Configuration::enableTX(), enterCLIMode(), Configuration::eraseStationData(), Configuration::factoryReset(), fireTestPacket(), Configuration::instance(), RadioManager::instance(), TXScheduler::instance(), jumpToBootloader(), StationData::len, StationData::magic, StationData::mmsi, StationData::name, StationData::portOffset, TXScheduler::queueMessage24(), Configuration::reportStationData(), Configuration::reportSystemData(), TXScheduler::reportTXStatus(), Configuration::reportXOTrimValue(), Configuration::setXOTrimValue(), RadioManager::setXOTrimValue(), STATION_DATA_MAGIC, RadioManager::stopTX(), Utils::toInt(), Utils::tokenize(), RadioManager::transmitCW(), Utils::trim(), StationData::type, writeOTPData(), and Configuration::writeStationData().
Referenced by processEvent().