AIS Transponder: EventPool::newRXPacket
newRXPacket()
RXPacket * EventPool::newRXPacket ()
Definition at line 127 of file Events.cpp.
{
  RXPacket *p = mRXPool.get();
  ASSERT_VALID_PTR(p);
  return p;
}
References ASSERT_VALID_PTR, ObjectPool< T >::get(), and mRXPool.
Referenced by Receiver::onBitClock(), Receiver::pushPacket(), and Receiver::Receiver().