AIS Transponder: RXPacket::addBit
addBit()
void RXPacket::addBit (uint8_t bit) private
Definition at line 119 of file RXPacket.cpp.
{
  //ASSERT(mSize < MAX_AIS_RX_PACKET_SIZE);
  uint16_t index = mState.mSize / 8;
  uint8_t offset = mState.mSize % 8;
  if ( bit )
    mState.mPacket[index] |= ( 1 << offset );
  else
    mState.mPacket[index] &= ~( 1 << offset );
  ++mState.mSize;
}
References bit(), and mState.
Referenced by addByte(), addFillBits(), and discardCRC().