AIS Transponder: Receiver::processNRZIBit
processNRZIBit()
Receiver::Action Receiver::processNRZIBit (uint8_t bit) protected
This method must complete in a few microseconds, worst case!
This is the longest operation undertaken here. Now that we use object pools and pointers, it completes in about 14us
Definition at line 172 of file Receiver.cpp.
{
  if ( mLastNRZIBit == 0xff )
    {
      mLastNRZIBit = bit;
      return NO_ACTION;
    }
  uint8_t decodedBit = !(mLastNRZIBit ^ bit);
  switch (mBitState) {
  case BIT_STATE_PREAMBLE_SYNC:
    {
      mLastNRZIBit = bit;
      mBitWindow <<= 1;
      mBitWindow |= decodedBit;
      /*
       * By checking for the last few preamble bits plus the HDLC start flag,
       * we gain enough confidence that this is not random noise.
       */
      //if ( mBitWindow == 0b1010101001111110 || mBitWindow == 0b0101010101111110 )
      if ( (mBitWindow & 0x0fff) == 0b101001111110 || (mBitWindow &0x0fff) == 0b010101111110 )
        {
          mBitState = BIT_STATE_IN_PACKET;
          mRXPacket->setChannel(mChannel);
        }
      break;
    }
  case BIT_STATE_IN_PACKET:
    {
      if ( mOneBitCount >= 7 || mRXPacket->size() >= MAX_AIS_RX_PACKET_SIZE - 2 )
        {
          // Start over
          return RESTART_RX;
        }
      mLastNRZIBit = bit;
      mBitWindow <<= 1;
      mBitWindow |= decodedBit;
      if ( (mBitWindow & 0x00ff) == 0x7E )
        {
          // We have a complete packet
          mBitState = BIT_STATE_PREAMBLE_SYNC;
          pushPacket();
          return RESTART_RX;
        }
      else
        {
          addBit(decodedBit);
        }
      break;
    }
  }
  return NO_ACTION;
}
References addBit(), BIT_STATE_IN_PACKET, BIT_STATE_PREAMBLE_SYNC, MAX_AIS_RX_PACKET_SIZE, mBitState, mBitWindow, mChannel, mLastNRZIBit, mOneBitCount, mRXPacket, NO_ACTION, pushPacket(), RESTART_RX, RXPacket::setChannel(), and RXPacket::size().
Referenced by onBitClock().