AIS Transponder: Error_Handler
Error_Handler()
void Error_Handler (void)
Referenced by __attribute__(), bsp_hw_init(), BusFault_Handler(), MemManage_Handler(), NMI_Handler(), SystemClock_Config(), and UsageFault_Handler().