AIS Transponder: printf_serial
printf_serial()
void printf_serial (const char * format, ...)
Definition at line 49 of file printf_serial.cpp.
{
  if ( Utils::inISR() )
    {
      Event *e = EventPool::instance().newEvent(DEBUG_EVENT);
      if ( e )
        {
          va_list list;
          va_start(list, format);
          vsnprintf(e->debugMessage.buffer, sizeof e->debugMessage, format, list);
          va_end(list);
          EventQueue::instance().push(e);
        }
    }
  else
    {
      va_list list;
      va_start(list, format);
      vsnprintf(__buffer, sizeof __buffer, format, list);
      va_end(list);
#ifdef MULTIPLEXED_OUTPUT
      DataTerminal::instance().write("DEBUG", __buffer);
#else
      bsp_write_string(__buffer);
#endif
    }
}
References bsp_write_string(), DebugMessage::buffer, DEBUG_EVENT, Event::debugMessage, Utils::inISR(), DataTerminal::instance(), EventQueue::instance(), EventPool::instance(), EventPool::newEvent(), EventQueue::push(), and DataTerminal::write().